name: Daily Auto Commit

on:
  schedule:
    - cron: '10 6 * * *'  # Daily at 06:10 UTC
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Dummy update step by 24f2002722@ds.study.iitm.ac.in
        run: |
          echo "Daily update at $(date -u)" > daily-log.txt

      - name: Commit and push changes
        run: |
          git config --local user.email "24f2002722@ds.study.iitm.ac.in"
          git config --local user.name "GitHub Actions"
          git add daily-log.txt
          git commit -m "Daily update [skip ci]" || echo "No changes to commit"
          git push

